import { useAlert } from 'react-alert';
import Head from 'next/head';
import 'twin.macro';

export default function Home() {
  const alert = useAlert();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <h1 tw="text-2xl text-sky-500 font-bold">Hello World</h1>
        <button onClick={() => alert.success('Hello World')}>test alert</button>
      </main>
    </div>
  );
}
